version: '3.8'

services:
  db:
    image: postgres:16
    container_name: cinema-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: vinisnzy
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
